baseURL = "/"
title = "暢鴻實業"
theme = "PaperMod"

enableRobotsTXT = true
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[languages]
  [languages.zh]
    contentDir = "content/zh"
    languageCode = "zh-TW"
    languageName = "中文"
    title = "暢鴻實業"
    weight = 1

  [languages.en]
    contentDir = "content/en"
    languageCode = "en-US"
    languageName = "English"
    title = "CHANG HOUNG LEATHER ENTERPRISE CO., LTD"
    weight = 2

[params]
  author = "CHANG HOUNG LEATHER ENTERPRISE CO., LTD"
  description = "OEM and ODM bicycle accessories manufacturer for export markets."
  disableThemeToggle = true
  ShowBreadCrumbs = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowCodeCopyButtons = true
  disableScrollToTop = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']
